import house_1 from './assets/house_1.jpg'
import house_2 from './assets/house_2.jpg'
import house_3 from './assets/house_3.jpg'
import house_4 from './assets/house_4.jpg'
import house_5 from './assets/house_5.jpg'
import house_6 from './assets/house_6.jpg'
import house_7 from './assets/house_7.jpg'
import house_8 from './assets/house_8.jpg'

export const data = [
    {
        title: "Stylist apartment in center of the city",
        imgSource: house_1,
        rating: 4.4,
        type: "Entire apartment . 2 beds",
        rooms: 2,
        location: "Helsinki , Finland",
        isSuperHost: true,
    },
    {
        title: "Cozy, peaceful and private room with...",
        imgSource: house_2,
        rating: 4.25,
        type: "Private room",
        rooms: 1,
        location: "Turku, Finland",
        isSuperHost: false,
    },
    {
        title: "Mordern House in a remote area",
        imgSource: house_3,
        rating: 4.96,
        type: "Entire house",
        rooms: 3,
        location: "Oulu, Finland",
        isSuperHost: false,
    },
    {
        title: "Stylist room in design district ",
        imgSource: house_4,
        rating: 4.85,
        type: "Entire apartment . 2 beds",
        rooms: 2,
        location: "Vaasa, Finland",
        isSuperHost: true,
    },
    {
        title: "Modern apartment close to nature",
        imgSource: house_5,
        rating: 4.54,
        type: "Private room",
        rooms: 1,
        location: "Turku, Finland",
        isSuperHost: false,
    },
    {
        title: "House in a remote area",
        imgSource: house_6,
        rating: 4.64,
        type: "Entire house",
        rooms: 3,
        location: "Helsinki, Finland",
        isSuperHost: false,
    },
    {
        title: "Luxury and Modern house",
        imgSource: house_7,
        rating: 4.4,
        type: "Entire House",
        rooms: 3,
        location: "Helsinki, Finland",
        isSuperHost: false,
    },
    {
        title: "Beutiful house out of the city",
        imgSource: house_8,
        rating: 4.5,
        type: "Entire House",
        rooms: 3,
        location: "Oulu, Finland",
        isSuperHost: false,
    },
    {
        title: "Stylist apartment in center of the city",
        imgSource: house_1,
        rating: 4.4,
        type: "Entire apartment . 2 beds",
        rooms: 2,
        location: "Helsinki , Finland",
        isSuperHost: true,
    },
    {
        title: "Cozy, peaceful and private room with...",
        imgSource: house_2,
        rating: 4.25,
        type: "Private room",
        rooms: 1,
        location: "Turku, Finland",
        isSuperHost: false,
    },
    {
        title: "Mordern House in a remote area",
        imgSource: house_3,
        rating: 4.96,
        type: "Entire house",
        rooms: 3,
        location: "Oulu, Finland",
        isSuperHost: false,
    },
    {
        title: "Stylist room in design district ",
        imgSource: house_4,
        rating: 4.85,
        type: "Entire apartment . 2 beds",
        rooms: 2,
        location: "Vaasa, Finland",
        isSuperHost: true,
    },
    {
        title: "Modern apartment close to nature",
        imgSource: house_5,
        rating: 4.54,
        type: "Private room",
        rooms: 1,
        location: "Turku, Finland",
        isSuperHost: false,
    },
    {
        title: "Modern apartment close to nature",
        imgSource: house_5,
        rating: 4.54,
        type: "Private room",
        rooms: 5,
        location: "Turku, Finland",
        isSuperHost: false,
    },
    {
        title: "House in a remote area",
        imgSource: house_6,
        rating: 4.64,
        type: "Entire house",
        rooms: 3,
        location: "Helsinki, Finland",
        isSuperHost: false,
    },
    {
        title: "Luxury and Modern house",
        imgSource: house_7,
        rating: 4.4,
        type: "Entire House",
        rooms: 3,
        location: "Helsinki, Finland",
        isSuperHost: false,
    },
    {
        title: "Beutiful house out of the city",
        imgSource: house_8,
        rating: 4.5,
        type: "Entire House",
        rooms: 3,
        location: "Oulu, Finland",
        isSuperHost: false,
    },
    {
        title: "Stylist apartment in center of the city",
        imgSource: house_1,
        rating: 4.4,
        type: "Entire apartment . 2 beds",
        rooms: 2,
        location: "Helsinki , Finland",
        isSuperHost: true,
    },
    {
        title: "Cozy, peaceful and private room with...",
        imgSource: house_2,
        rating: 4.25,
        type: "Private room",
        rooms: 1,
        location: "Turku, Finland",
        isSuperHost: false,
    },
    {
        title: "Mordern House in a remote area",
        imgSource: house_3,
        rating: 4.96,
        type: "Entire house",
        rooms: 3,
        location: "Oulu, Finland",
        isSuperHost: false,
    },
    {
        title: "Stylist room in design district ",
        imgSource: house_4,
        rating: 4.85,
        type: "Entire apartment . 2 beds",
        rooms: 2,
        location: "Vaasa, Finland",
        isSuperHost: true,
    },
    {
        title: "Modern apartment close to nature",
        imgSource: house_5,
        rating: 4.54,
        type: "Private room",
        rooms: 1,
        location: "Turku, Finland",
        isSuperHost: false,
    },
    {
        title: "House in a remote area",
        imgSource: house_6,
        rating: 4.64,
        type: "Entire house",
        rooms: 3,
        location: "Helsinki, Finland",
        isSuperHost: false,
    },
    {
        title: "Luxury and Modern house",
        imgSource: house_7,
        rating: 4.4,
        type: "Entire House",
        rooms: 3,
        location: "Helsinki, Finland",
        isSuperHost: false,
    },
    {
        title: "Beutiful house out of the city",
        imgSource: house_8,
        rating: 4.5,
        type: "Entire House",
        rooms: 3,
        location: "Oulu, Finland",
        isSuperHost: false,
    },
    {
        title: "Stylist apartment in center of the city",
        imgSource: house_1,
        rating: 4.4,
        type: "Entire apartment . 2 beds",
        rooms: 2,
        location: "Helsinki , Finland",
        isSuperHost: true,
    },
    {
        title: "Cozy, peaceful and private room with...",
        imgSource: house_2,
        rating: 4.25,
        type: "Private room",
        rooms: 1,
        location: "Turku, Finland",
        isSuperHost: false,
    },
    {
        title: "Mordern House in a remote area",
        imgSource: house_3,
        rating: 4.96,
        type: "Entire house",
        rooms: 3,
        location: "Oulu, Finland",
        isSuperHost: false,
    },
    {
        title: "Stylist room in design district ",
        imgSource: house_4,
        rating: 4.85,
        type: "Entire apartment . 2 beds",
        rooms: 2,
        location: "Vaasa, Finland",
        isSuperHost: true,
    },
    {
        title: "Modern apartment close to nature",
        imgSource: house_5,
        rating: 4.54,
        type: "Private room",
        rooms: 1,
        location: "Turku, Finland",
        isSuperHost: false,
    },
    {
        title: "House in a remote area",
        imgSource: house_6,
        rating: 4.64,
        type: "Entire house",
        rooms: 3,
        location: "Helsinki, Finland",
        isSuperHost: false,
    },
    {
        title: "Luxury and Modern house",
        imgSource: house_7,
        rating: 4.4,
        type: "Entire House",
        rooms: 3,
        location: "Helsinki, Finland",
        isSuperHost: false,
    },
    {
        title: "Beutiful house out of the city",
        imgSource: house_8,
        rating: 4.5,
        type: "Entire House",
        rooms: 3,
        location: "Oulu, Finland",
        isSuperHost: false,
    },
];